# Generated by Django 3.1.3 on 2020-11-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201105_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
